"""Machine-friendly formula registry derived from PE_Module_4.pdf.

Source PDF:
/Users/kavishapurohit/Desktop/Private Equity Course/PE_Module_4.pdf
"""

FORMULAS = [
    {
        "id": "equity_value_dcf",
        "category": "dcf",
        "source_type": "explicit_pdf",
        "pages": [8, 12, 35],
        "name": "Equity value from discounted cash flow",
        "latex": r"\text{Equity Value} = \sum_{t=1}^{n} \frac{CF_t}{(1 + WACC)^t} + TV_n + (SA - M - NFP)",
        "python": "sum(cf_t / ((1 + wacc) ** t) for t, cf_t in enumerate(cash_flows, start=1)) + tv_n + (surplus_assets - minorities - net_financial_position)",
        "variables": ["CF_t", "WACC", "TV_n", "SA", "M", "NFP"],
        "notes": "Deck notation adds surplus assets and subtracts minorities and net financial position after enterprise value.",
    },
    {
        "id": "ebitda_bridge",
        "category": "income_statement",
        "source_type": "explicit_pdf",
        "pages": [14],
        "name": "EBITDA bridge",
        "latex": r"EBITDA = Sales + Other\ Operating\ Revenues - Operating\ Costs",
        "python": "ebitda = sales + other_operating_revenues - operating_costs",
        "variables": ["Sales", "Other Operating Revenues", "Operating Costs"],
        "notes": "Shown directly on the P&L bridge slide.",
    },
    {
        "id": "ebit_bridge",
        "category": "income_statement",
        "source_type": "explicit_pdf",
        "pages": [14],
        "name": "EBIT bridge",
        "latex": r"EBIT = EBITDA - Depreciation",
        "python": "ebit = ebitda - depreciation",
        "variables": ["EBITDA", "Depreciation"],
        "notes": "Deck labels EBIT as operating profit.",
    },
    {
        "id": "ebt_bridge",
        "category": "income_statement",
        "source_type": "explicit_pdf",
        "pages": [14],
        "name": "EBT bridge",
        "latex": r"EBT = EBIT + Other\ Income - Interest\ Expenses",
        "python": "ebt = ebit + other_income - interest_expenses",
        "variables": ["EBIT", "Other Income", "Interest Expenses"],
        "notes": "Other income is noted as typically financial and non-operating.",
    },
    {
        "id": "net_income_bridge",
        "category": "income_statement",
        "source_type": "explicit_pdf",
        "pages": [14],
        "name": "Net income bridge",
        "latex": r"Net\ Income = EBT - Income\ Taxes",
        "python": "net_income = ebt - income_taxes",
        "variables": ["EBT", "Income Taxes"],
        "notes": "Standard bottom-line bridge shown in the deck.",
    },
    {
        "id": "free_cash_flow_firm",
        "category": "dcf",
        "source_type": "explicit_pdf",
        "pages": [15, 29],
        "name": "Free cash flow for the firm",
        "latex": r"CF = EBIT - Income\ Taxes + Depreciation - Increase\ in\ Net\ Working\ Capital - CAPEX",
        "python": "cash_flow = ebit - income_taxes + depreciation - increase_in_nwc - capex",
        "variables": ["EBIT", "Income Taxes", "Depreciation", "Increase in Net Working Capital", "CAPEX"],
        "notes": "Deck calls this free CF for the firm or unlevered cash flow.",
    },
    {
        "id": "after_tax_cost_of_debt",
        "category": "wacc",
        "source_type": "explicit_pdf",
        "pages": [17, 30, 31],
        "name": "After-tax cost of debt",
        "latex": r"id^* = id (1 - t)",
        "python": "cost_of_debt_after_tax = cost_of_debt * (1 - tax_rate)",
        "variables": ["id", "t"],
        "notes": "Deck uses id* for net cost of debt capital.",
    },
    {
        "id": "capm_cost_of_equity",
        "category": "wacc",
        "source_type": "explicit_pdf",
        "pages": [18, 30, 32],
        "name": "CAPM cost of equity",
        "latex": r"ie = r_f + \beta (r_m - r_f)",
        "python": "cost_of_equity = risk_free_rate + beta * (market_return - risk_free_rate)",
        "variables": ["r_f", "beta", "r_m"],
        "notes": "Deck defines rm - rf as the market risk premium.",
    },
    {
        "id": "beta_unlevered",
        "category": "wacc",
        "source_type": "explicit_pdf",
        "pages": [20, 30, 31],
        "name": "Unlevered beta",
        "latex": r"\beta_u = \frac{\beta}{1 + (1 - t)(D/E)}",
        "python": "beta_unlevered = beta / (1 + (1 - tax_rate) * (debt / equity))",
        "variables": ["beta", "t", "D", "E"],
        "notes": "Uses comparable-company capital structure.",
    },
    {
        "id": "beta_relevered",
        "category": "wacc",
        "source_type": "explicit_pdf",
        "pages": [20, 30, 31],
        "name": "Relevered beta",
        "latex": r"\beta^* = \beta_u \times [1 + (1 - t)(D/E)^*]",
        "python": "beta_relevered = beta_unlevered * (1 + (1 - tax_rate) * target_debt_to_equity)",
        "variables": ["beta_u", "t", "(D/E)*"],
        "notes": "Starred terms refer to target-company leverage.",
    },
    {
        "id": "wacc",
        "category": "wacc",
        "source_type": "explicit_pdf",
        "pages": [21, 30, 32],
        "name": "Weighted average cost of capital",
        "latex": r"WACC = id^* \times \frac{D}{D+E} + ie \times \frac{E}{D+E}",
        "python": "wacc = cost_of_debt_after_tax * (debt / (debt + equity)) + cost_of_equity * (equity / (debt + equity))",
        "variables": ["id*", "ie", "D", "E"],
        "notes": "Deck writes this as iWACC.",
    },
    {
        "id": "terminal_value_deck",
        "category": "dcf",
        "source_type": "explicit_pdf",
        "pages": [22, 33],
        "name": "Terminal value term as shown in the deck",
        "latex": r"TV_n = \frac{CF_n \times (1 + g)}{(WACC - g)(1 + WACC)^n}",
        "python": "terminal_value_present = (cash_flow_n * (1 + g)) / ((wacc - g) * ((1 + wacc) ** n))",
        "variables": ["CF_n", "g", "WACC", "n"],
        "notes": "This is effectively present value of terminal value because the deck includes discounting inside the formula.",
    },
    {
        "id": "exit_ev_multiple",
        "category": "pe_exit",
        "source_type": "worked_example",
        "pages": [40, 42],
        "name": "Exit enterprise value from EBITDA multiple",
        "latex": r"EV_{exit} = EBITDA_{exit} \times Exit\ Multiple",
        "python": "exit_enterprise_value = exit_ebitda * exit_multiple",
        "variables": ["EBITDA_exit", "Exit Multiple"],
        "notes": "Derived from the PE exit example where 6,000 EBITDA at 4.0x gives 24,000 EV.",
    },
    {
        "id": "exit_equity_value",
        "category": "pe_exit",
        "source_type": "worked_example",
        "pages": [42],
        "name": "Exit equity value",
        "latex": r"Equity\ Value_{exit} = EV_{exit} - NFP_{exit}",
        "python": "exit_equity_value = exit_enterprise_value - exit_nfp",
        "variables": ["EV_exit", "NFP_exit"],
        "notes": "Used directly in the PE worked example.",
    },
    {
        "id": "future_value_investment",
        "category": "vc_method",
        "source_type": "explicit_pdf",
        "pages": [48],
        "name": "Future value of the investment",
        "latex": r"Future\ Value\ of\ the\ Investment = Value\ of\ the\ Investment \times (1 + Expected\ IRR)^n",
        "python": "future_value_of_investment = investment_value * ((1 + expected_irr) ** n)",
        "variables": ["Investment Value", "Expected IRR", "n"],
        "notes": "Shown in the VC method section.",
    },
    {
        "id": "vc_terminal_value_pe",
        "category": "vc_method",
        "source_type": "explicit_pdf",
        "pages": [49],
        "name": "VC terminal value using P/E",
        "latex": r"TV = Net\ Income_N \times P/E\ Ratio",
        "python": "terminal_value = terminal_year_net_income * pe_ratio",
        "variables": ["Net Income_N", "P/E Ratio"],
        "notes": "Explicitly presented as an alternative TV method in the VC section.",
    },
    {
        "id": "vc_percent_shares",
        "category": "vc_method",
        "source_type": "explicit_pdf",
        "pages": [50],
        "name": "Required PE ownership",
        "latex": r"\%\ PE\ Shares = \frac{Future\ Value\ of\ the\ Investment}{TV}",
        "python": "required_share_percent = future_value_of_investment / terminal_value",
        "variables": ["Future Value of the Investment", "TV"],
        "notes": "VC method ownership formula shown directly in the slide.",
    },
    {
        "id": "vc_new_shares",
        "category": "vc_method",
        "source_type": "explicit_pdf",
        "pages": [51],
        "name": "Number of new shares",
        "latex": r"Number\ of\ New\ Shares = \frac{Existing\ Shares \times \%\ Shares}{1 - \%\ Shares}",
        "python": "new_shares = (existing_shares * share_percent) / (1 - share_percent)",
        "variables": ["Existing Shares", "% Shares"],
        "notes": "Used to calculate issuance required for the investor target stake.",
    },
    {
        "id": "vc_new_share_price",
        "category": "vc_method",
        "source_type": "explicit_pdf",
        "pages": [52],
        "name": "Price of new shares",
        "latex": r"Price\ of\ New\ Shares = \frac{Value\ of\ the\ Investment}{Number\ of\ New\ Shares}",
        "python": "new_share_price = investment_value / new_shares",
        "variables": ["Value of the Investment", "Number of New Shares"],
        "notes": "Final pricing step in the VC example.",
    },
]


def get_formulas_by_category(category: str):
    return [formula for formula in FORMULAS if formula["category"] == category]


def get_explicit_pdf_formulas():
    return [formula for formula in FORMULAS if formula["source_type"] == "explicit_pdf"]
